version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mongo
      - redis
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: dte
      POSTGRES_PASSWORD: dte
      POSTGRES_DB: factura
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: dte
      MONGO_INITDB_ROOT_PASSWORD: dte
  redis:
    image: redis:latest
